### ISSUE TITLE
Changing Function Name?

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-advanced-functions-first-class-functions-lab#1]
I feel like the #selectDifferentDrivers function should not be called that because we're selecting the same drivers. I actually wrote a function that enables us to nondestructively take the values in the array that are not values in the second argument, before I realized the opposite. (I know it's my fault for not reading the spec well, but I do think the function name is deceiving)

**Comment by drakeltheryuujin** [comment]
Hi @AkaKuro4Ever,

The materials have been updated to address this issue. Thanks for contributing! 💙
