### ISSUE TITLE
Pull Request, Tests And Submit Not Working

### ISSUE THREAD

**Issue by Nanton83** [learn-co-curriculum/js-advanced-functions-first-class-functions-lab#3]

**Comment by rrcobb** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Comment by Nanton83** [comment]
Hey Robert,

I figured out that I was pulling from learn-co directly and not learn-co students. I am now manually forking and cloning. This seems to have fixed my issue. Thanks!
