### ISSUE TITLE
SelectDifferentDrivers

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-advanced-functions-first-class-functions-lab#4]
This function and what it expects is really unclear. AND the tests pass if you just pass in one of the two functions (returnFirstTwoDrivers or  returnLastTwoDrivers. And the suggested solution uses a function called whichDrivers, that isn't really clear, nor are the steps it would take to get there, and even the tech coach was stymied. Thanks for considering changing this for other students. 
![Screen Shot 2020-02-19 at 12 46 30 PM](https://user-images.githubusercontent.com/18649892/74859924-dc14f100-5315-11ea-8fc3-3fd51065dc6d.png)

This code passed. The tech coach had suggested just adding in one of the functions first, to see what the response would be, and that's how we figured out it passed. 

if the goal is for us to use the selectingDrivers array, then you should give students more of a hint about that, or move it to just before this final function. Then you should change the solution code. And also, it would be great to see in the lab or lesson whether we can include the two functions just as an array, with brackets, as an argument (it doesn't, but showing us how to destructure here, or emphasizing the pattern of putting multiple functions into an array to pass in would be really helpful). 

solution code to be changed to make things easier to understand 
![Screen Shot 2020-02-19 at 12 53 01 PM](https://user-images.githubusercontent.com/18649892/74860894-6ca00100-5317-11ea-9a82-2d03f5f5cad6.png)

screenshot of functions in bracketed array: 
![Screen Shot 2020-02-19 at 12 56 14 PM](https://user-images.githubusercontent.com/18649892/74860784-38c4db80-5317-11ea-9b02-4a2096b157d5.png)

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback. The lesson has been updated to clarify the requirements.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

Thank you for contributing to the Flatiron School curriculum. 💙
